language: c
os: linux
dist: bionic

jobs:
  include:
    - os: linux
      compiler: "gcc-7"
      env: BUILD='Debug' CC=gcc-7 CXX=g++-7
      dist: bionic
      addons: *gcc7

    - os: linux
      compiler: "gcc-7"
      env: BUILD='Release' CC=gcc-7 CXX=g++-7
      dist: bionic
      addons: *gcc7

    - os: linux
      arch: arm64
      compiler: "gcc"
      env: BUILD='Release'
      dist: bionic

allow_failures:
    - os: linux
      compiler: "arm-none-eabi-gcc"
      env: BUILD='Release' AR=arm-none-eabi-ar
           TOOLCHAIN=-DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-cross-arm-none-eabi.cmake
      dist: bionic
      addons:
        apt:
          sources:
          - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
          packages:
          - gcc-arm-embedded

script:
  - cmake --version
  - ${CC} --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD} ${TOOLCHAIN} ..
  - cmake --build .

notifications:
  email:
    on_success: never
    on_failure: never