language: c
os: linux
dist: bionic

jobs:
  include:
    - os: linux
      compiler: "gcc-7"
      env: BUILD='Debug' CC=gcc-7 CXX=g++-7 OPT=-DLIBJ1939_BUILD_EXAMPLE=1
      dist: bionic
      addons: *gcc7

    - os: linux
      compiler: "gcc-7"
      env: BUILD='Release' CC=gcc-7 CXX=g++-7 OPT=-DLIBJ1939_BUILD_EXAMPLE=1
      dist: bionic
      addons: *gcc7

    - os: linux
      arch: arm64
      compiler: "gcc"
      env: BUILD='Release' OPT=-DLIBJ1939_BUILD_EXAMPLE=1
      dist: bionic
      addons: *gcc7

    - os: linux
      compiler: "gcc"
      env: BUILD='Release'
           TOOLCHAIN=-DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-cross-arm-none-eabi.cmake
      dist: bionic
      addons:
        apt:
          sources:
          - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
          packages:
          - gcc-arm-embedded

before_install:
  - sudo apt-get -y install linux-headers-generic
 
script:
  - cmake --version
  - ${CC} --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD} ${TOOLCHAIN} ${OPT} ..
  - VERBOSE=1 cmake --build .

notifications:
  email:
    on_success: never
    on_failure: never
